"""empty message

Revision ID: 3c82e2899b00
Revises: 2a26ac80bcd1
Create Date: 2020-05-07 14:40:42.439720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c82e2899b00'
down_revision = '2a26ac80bcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('INSERT INTO todolists (name) VALUES (\'Default\');')
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.execute('UPDATE todos SET list_id = 1 WHERE list_id IS NULL;')
    op.alter_column('todos', 'list_id', nullable=False)
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
